fix deprecated pkg_resources in higher version of setuptools
setuptools>82.0.0 has removed pkg_resources module,
which cause:

ModuleNotFoundError: No module named 'pkg_resources'

this commit adds upper limit of setuptools version